export const allRobots = [
  {
    id: 1,
    name: 'Funky Joe',
    powermove: 'Spinning Turtle',
    experience: 5,
    outOfOrder: false,
    avatar: 'https://robohash.org/funky-joe.png',
  },
  {
    id: 2,
    name: 'Ternary Tim',
    powermove: 'Type Coercion',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/ternary-tim.png',
  },
  {
    id: 3,
    name: 'Amazing Helen',
    powermove: 'Observing Ostrich',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/amazing-helen.png',
  },
  {
    id: 4,
    name: 'Hilarious Jack',
    powermove: 'Yielding Yak',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/hilarious-jack.png',
  },
  {
    id: 5,
    name: 'Productive Paula',
    powermove: 'Celebrating Lobster',
    experience: 11,
    outOfOrder: false,
    avatar: 'https://robohash.org/productive-paula.png',
  },
  {
    id: 6,
    name: 'Flexible Stuart',
    powermove: 'Searching Swan',
    experience: 10,
    outOfOrder: false,
    avatar: 'https://robohash.org/flexible-stuart.png',
  },
  {
    id: 7,
    name: 'Lisa "Root" Allen',
    powermove: 'Fork Join',
    experience: 15,
    outOfOrder: false,
    avatar: 'https://robohash.org/lisa-root-allen.png',
  },
  {
    id: 8,
    name: 'Decisive Sarah',
    powermove: 'Smashing Pineapple',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/decisive-sarah.png',
  },
  {
    id: 9,
    name: 'Efficient Linda',
    powermove: 'Relaxing Sloth',
    experience: 7,
    outOfOrder: false,
    avatar: 'https://robohash.org/erfficient-linda.png',
  },
  {
    id: 10,
    name: 'Variable Vicky',
    powermove: 'Thread Drop',
    experience: 12,
    outOfOrder: true,
    avatar: 'https://robohash.org/variable-vicky.png',
  },
  {
    id: 11,
    name: 'Dancing Jorge',
    powermove: 'Privilege Escalation',
    experience: 7,
    outOfOrder: false,
    avatar: 'https://robohash.org/dancing-jorge.png',
  },
  {
    id: 12,
    name: 'Fred "Detail-Oriented" Miller',
    powermove: 'Deep Cloning',
    experience: 9,
    outOfOrder: false,
    avatar: 'https://robohash.org/fred-miller.png',
  },
  {
    id: 13,
    name: 'General Garcia',
    powermove: 'Constructor Overloading',
    experience: 12,
    outOfOrder: false,
    avatar: 'https://robohash.org/gerneral-garcia.png',
  },
  {
    id: 14,
    name: 'Infinity Sam',
    powermove: 'Database Migration',
    experience: 11,
    outOfOrder: false,
    avatar: 'https://robohash.org/infinity-sam.png',
  },
  {
    id: 15,
    name: 'Responsible Stella',
    powermove: 'Integer Factorization',
    experience: 13,
    outOfOrder: false,
    avatar: 'https://robohash.org/responsible-stella.png',
  },
  {
    id: 16,
    name: 'Solid Sandra',
    powermove: 'Monkey Patching',
    experience: 8,
    outOfOrder: true,
    avatar: 'https://robohash.org/solid-sandra.png',
  },
  {
    id: 17,
    name: 'Danger Dan',
    powermove: 'Floating Unicorn',
    experience: 15,
    outOfOrder: false,
    avatar: 'https://robohash.org/danger-dan.png',
  },
  {
    id: 18,
    name: 'Exceptional Alice',
    powermove: 'Heap Allocation',
    experience: 12,
    outOfOrder: false,
    avatar: 'https://robohash.org/exceptional-alice.png',
  },
  {
    id: 19,
    name: 'Sliding Stephanie',
    powermove: 'Cache Invalidation',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/sliding-stephanie.png',
  },
  {
    id: 20,
    name: 'Excellent Erin',
    powermove: 'Changing Chameleon',
    experience: 7,
    outOfOrder: true,
    avatar: 'https://robohash.org/excellent-erin.png',
  },
  {
    id: 21,
    name: 'Versatile Hector',
    powermove: 'Exception Handling',
    experience: 9,
    outOfOrder: false,
    avatar: 'https://robohash.org/versatile-hector.png',
  },
  {
    id: 22,
    name: 'Rebasing Isabel',
    powermove: 'Path Traversal',
    experience: 10,
    outOfOrder: false,
    avatar: 'https://robohash.org/rebasing-isabel.png',
  },
  {
    id: 23,
    name: 'Reflective Jim',
    powermove: 'Chair Freeze',
    experience: 6,
    outOfOrder: true,
    avatar: 'https://robohash.org/reflective-jim.png',
  },
  {
    id: 24,
    name: 'Merge Mike',
    powermove: 'Protective Otter',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/merge-mike.png',
  },
  {
    id: 25,
    name: 'Charismatic Valeria',
    powermove: 'Secondary Indexing',
    experience: 7,
    outOfOrder: false,
    avatar: 'https://robohash.org/charismatic-valeria.png',
  },
  {
    id: 26,
    name: 'Confident Carol',
    powermove: 'Brute Force Detection',
    experience: 9,
    outOfOrder: false,
    avatar: 'https://robohash.org/confident-carol.png',
  },
  {
    id: 27,
    name: 'Elastic Eddie',
    powermove: 'Dabbing Penguin',
    experience: 11,
    outOfOrder: false,
    avatar: 'https://robohash.org/elastic-eddie.png',
  },
  {
    id: 28,
    name: 'Endearing Fred',
    powermove: 'Lazy Loading',
    experience: 9,
    outOfOrder: false,
    avatar: 'https://robohash.org/endearing-fred.png',
  },
  {
    id: 29,
    name: 'Positive Anna',
    powermove: 'Tree Shaking',
    experience: 10,
    outOfOrder: false,
    avatar: 'https://robohash.org/positive-anna.png',
  },
  {
    id: 30,
    name: 'Hipster Kate',
    powermove: 'Dancing Frog',
    experience: 10,
    outOfOrder: false,
    avatar: 'https://robohash.org/hipster-kate.png',
  },
  {
    id: 31,
    name: 'Honest Mark',
    powermove: 'Argument Destructuring',
    experience: 8,
    outOfOrder: false,
    avatar: 'https://robohash.org/honest-mark.png',
  },
  {
    id: 32,
    name: 'Crazy Brian',
    powermove: 'Sleeping Crocodile',
    experience: 7,
    outOfOrder: true,
    avatar: 'https://robohash.org/crazy-brian.png',
  },
  {
    id: 33,
    name: 'Anxious Andy',
    powermove: 'Implicit Invocation',
    experience: 6,
    outOfOrder: true,
    avatar: 'https://robohash.org/anxious-andy.png',
  },
  {
    id: 34,
    name: 'Agile Anna',
    powermove: 'Pretzel Hop',
    experience: 5,
    outOfOrder: false,
    avatar: 'https://robohash.org/agile-anna.png',
  },
  {
    id: 35,
    name: 'Victor "Void" Smith',
    powermove: 'Swimming Ferret',
    experience: 9,
    outOfOrder: false,
    avatar: 'https://robohash.org/victor-void-smith.png',
  },
  {
    id: 36,
    name: 'Functional Chris',
    powermove: 'Subscribing Kangaroo',
    experience: 7,
    outOfOrder: false,
    avatar: 'https://robohash.org/functional-chris.png',
  },
  {
    id: 37,
    name: 'Eloquent Teresa',
    powermove: 'Just-in-time Compilation',
    experience: 10,
    outOfOrder: false,
    avatar: 'https://robohash.org/eloquent-teresa.png',
  },
  {
    id: 38,
    name: 'Spinning Christina',
    powermove: 'Optional Chaining',
    experience: 11,
    outOfOrder: false,
    avatar: 'https://robohash.org/spinning-christina.png',
  },
  {
    id: 39,
    name: 'Zero-Downtime Sophie',
    powermove: 'Duck Typing',
    experience: 7,
    outOfOrder: false,
    avatar: 'https://robohash.org/zero-downtime-sophie.png',
  },
  {
    id: 40,
    name: 'Rational Randy',
    powermove: 'Kicking Koala',
    experience: 12,
    outOfOrder: false,
    avatar: 'https://robohash.org/rational-randy.png',
  },
];


export const danceOffs = [
  {
    id: 4032,
    dancedAt: '2022-06-13T12:18:42.905Z',
    winner: {
      id: 15,
      name: 'Responsible Stella',
      powermove: 'Integer Factorization',
      experience: 13,
      outOfOrder: false,
      avatar: 'https://robohash.org/responsible-stella.png',
    },
    loser: {
      id: 34,
      name: 'Agile Anna',
      powermove: 'Pretzel Hop',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/agile-anna.png',
    },
  },
  {
    id: 4031,
    dancedAt: '2022-06-13T12:18:42.896Z',
    winner: {
      id: 22,
      name: 'Rebasing Isabel',
      powermove: 'Path Traversal',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/rebasing-isabel.png',
    },
    loser: {
      id: 35,
      name: 'Victor "Void" Smith',
      powermove: 'Swimming Ferret',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/victor-void-smith.png',
    },
  },
  {
    id: 4030,
    dancedAt: '2022-06-13T12:18:42.803Z',
    winner: {
      id: 3,
      name: 'Amazing Helen',
      powermove: 'Observing Ostrich',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/amazing-helen.png',
    },
    loser: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
  },
  {
    id: 4029,
    dancedAt: '2022-06-13T12:18:42.796Z',
    winner: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 4028,
    dancedAt: '2022-06-13T12:18:42.767Z',
    winner: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
    loser: {
      id: 4,
      name: 'Hilarious Jack',
      powermove: 'Yielding Yak',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/hilarious-jack.png',
    },
  },
  {
    id: 4027,
    dancedAt: '2022-06-13T09:10:04.917Z',
    winner: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 4026,
    dancedAt: '2022-06-13T09:10:04.906Z',
    winner: {
      id: 15,
      name: 'Responsible Stella',
      powermove: 'Integer Factorization',
      experience: 13,
      outOfOrder: false,
      avatar: 'https://robohash.org/responsible-stella.png',
    },
    loser: {
      id: 9,
      name: 'Efficient Linda',
      powermove: 'Relaxing Sloth',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/erfficient-linda.png',
    },
  },
  {
    id: 4025,
    dancedAt: '2022-06-13T09:10:04.813Z',
    winner: {
      id: 34,
      name: 'Agile Anna',
      powermove: 'Pretzel Hop',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/agile-anna.png',
    },
    loser: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
  },
  {
    id: 4024,
    dancedAt: '2022-06-13T09:10:04.800Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 2,
      name: 'Ternary Tim',
      powermove: 'Type Coercion',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/ternary-tim.png',
    },
  },
  {
    id: 4023,
    dancedAt: '2022-06-13T09:10:04.197Z',
    winner: {
      id: 36,
      name: 'Functional Chris',
      powermove: 'Subscribing Kangaroo',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/functional-chris.png',
    },
    loser: {
      id: 37,
      name: 'Eloquent Teresa',
      powermove: 'Just-in-time Compilation',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/eloquent-teresa.png',
    },
  },
  {
    id: 4022,
    dancedAt: '2022-06-13T00:01:14.756Z',
    winner: {
      id: 13,
      name: 'General Garcia',
      powermove: 'Constructor Overloading',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/gerneral-garcia.png',
    },
    loser: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
  },
  {
    id: 4021,
    dancedAt: '2022-06-13T00:01:13.729Z',
    winner: {
      id: 36,
      name: 'Functional Chris',
      powermove: 'Subscribing Kangaroo',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/functional-chris.png',
    },
    loser: {
      id: 4,
      name: 'Hilarious Jack',
      powermove: 'Yielding Yak',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/hilarious-jack.png',
    },
  },
  {
    id: 4020,
    dancedAt: '2022-06-13T00:01:12.617Z',
    winner: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
    loser: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
  },
  {
    id: 4019,
    dancedAt: '2022-06-13T00:01:12.299Z',
    winner: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
    loser: {
      id: 9,
      name: 'Efficient Linda',
      powermove: 'Relaxing Sloth',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/erfficient-linda.png',
    },
  },
  {
    id: 4018,
    dancedAt: '2022-06-12T20:38:10.362Z',
    winner: {
      id: 9,
      name: 'Efficient Linda',
      powermove: 'Relaxing Sloth',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/erfficient-linda.png',
    },
    loser: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
  },
  {
    id: 4017,
    dancedAt: '2022-06-12T20:38:08.765Z',
    winner: {
      id: 35,
      name: 'Victor "Void" Smith',
      powermove: 'Swimming Ferret',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/victor-void-smith.png',
    },
    loser: {
      id: 8,
      name: 'Decisive Sarah',
      powermove: 'Smashing Pineapple',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/decisive-sarah.png',
    },
  },
  {
    id: 4016,
    dancedAt: '2022-06-12T20:38:07.180Z',
    winner: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
    loser: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
  },
  {
    id: 4015,
    dancedAt: '2022-06-12T20:38:01.311Z',
    winner: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 4014,
    dancedAt: '2022-06-12T11:48:19.370Z',
    winner: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
    loser: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
  },
  {
    id: 4013,
    dancedAt: '2022-06-12T11:47:58.200Z',
    winner: {
      id: 13,
      name: 'General Garcia',
      powermove: 'Constructor Overloading',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/gerneral-garcia.png',
    },
    loser: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
  },
  {
    id: 4012,
    dancedAt: '2022-06-12T10:56:05.923Z',
    winner: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
    loser: {
      id: 27,
      name: 'Elastic Eddie',
      powermove: 'Dabbing Penguin',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/elastic-eddie.png',
    },
  },
  {
    id: 4011,
    dancedAt: '2022-06-12T10:56:03.456Z',
    winner: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
    loser: {
      id: 34,
      name: 'Agile Anna',
      powermove: 'Pretzel Hop',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/agile-anna.png',
    },
  },
  {
    id: 4010,
    dancedAt: '2022-06-12T10:52:04.249Z',
    winner: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
    loser: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
  },
  {
    id: 4009,
    dancedAt: '2022-06-12T10:52:01.881Z',
    winner: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 4007,
    dancedAt: '2022-06-12T07:36:35.596Z',
    winner: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
    loser: {
      id: 26,
      name: 'Confident Carol',
      powermove: 'Brute Force Detection',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/confident-carol.png',
    },
  },
  {
    id: 4008,
    dancedAt: '2022-06-12T07:36:35.455Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
  },
  {
    id: 4005,
    dancedAt: '2022-06-12T07:36:35.238Z',
    winner: {
      id: 30,
      name: 'Hipster Kate',
      powermove: 'Dancing Frog',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/hipster-kate.png',
    },
    loser: {
      id: 22,
      name: 'Rebasing Isabel',
      powermove: 'Path Traversal',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/rebasing-isabel.png',
    },
  },
  {
    id: 4006,
    dancedAt: '2022-06-12T07:36:35.092Z',
    winner: {
      id: 24,
      name: 'Merge Mike',
      powermove: 'Protective Otter',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/merge-mike.png',
    },
    loser: {
      id: 36,
      name: 'Functional Chris',
      powermove: 'Subscribing Kangaroo',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/functional-chris.png',
    },
  },
  {
    id: 4004,
    dancedAt: '2022-06-12T07:36:34.920Z',
    winner: {
      id: 11,
      name: 'Dancing Jorge',
      powermove: 'Privilege Escalation',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/dancing-jorge.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 4003,
    dancedAt: '2022-06-12T07:13:21.197Z',
    winner: {
      id: 36,
      name: 'Functional Chris',
      powermove: 'Subscribing Kangaroo',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/functional-chris.png',
    },
    loser: {
      id: 18,
      name: 'Exceptional Alice',
      powermove: 'Heap Allocation',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/exceptional-alice.png',
    },
  },
  {
    id: 4002,
    dancedAt: '2022-06-12T07:13:21.067Z',
    winner: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
    loser: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
  },
  {
    id: 4001,
    dancedAt: '2022-06-12T07:13:20.925Z',
    winner: {
      id: 27,
      name: 'Elastic Eddie',
      powermove: 'Dabbing Penguin',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/elastic-eddie.png',
    },
    loser: {
      id: 26,
      name: 'Confident Carol',
      powermove: 'Brute Force Detection',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/confident-carol.png',
    },
  },
  {
    id: 4000,
    dancedAt: '2022-06-12T07:13:20.785Z',
    winner: {
      id: 4,
      name: 'Hilarious Jack',
      powermove: 'Yielding Yak',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/hilarious-jack.png',
    },
    loser: {
      id: 24,
      name: 'Merge Mike',
      powermove: 'Protective Otter',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/merge-mike.png',
    },
  },
  {
    id: 3999,
    dancedAt: '2022-06-12T07:13:20.333Z',
    winner: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
    loser: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
  },
  {
    id: 3998,
    dancedAt: '2022-06-12T07:12:48.257Z',
    winner: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
    loser: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
  },
  {
    id: 3997,
    dancedAt: '2022-06-12T07:12:47.979Z',
    winner: {
      id: 35,
      name: 'Victor "Void" Smith',
      powermove: 'Swimming Ferret',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/victor-void-smith.png',
    },
    loser: {
      id: 30,
      name: 'Hipster Kate',
      powermove: 'Dancing Frog',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/hipster-kate.png',
    },
  },
  {
    id: 3996,
    dancedAt: '2022-06-12T07:12:47.706Z',
    winner: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
    loser: {
      id: 22,
      name: 'Rebasing Isabel',
      powermove: 'Path Traversal',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/rebasing-isabel.png',
    },
  },
  {
    id: 3995,
    dancedAt: '2022-06-12T07:12:47.396Z',
    winner: {
      id: 4,
      name: 'Hilarious Jack',
      powermove: 'Yielding Yak',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/hilarious-jack.png',
    },
    loser: {
      id: 9,
      name: 'Efficient Linda',
      powermove: 'Relaxing Sloth',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/erfficient-linda.png',
    },
  },
  {
    id: 3994,
    dancedAt: '2022-06-12T07:12:46.713Z',
    winner: {
      id: 18,
      name: 'Exceptional Alice',
      powermove: 'Heap Allocation',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/exceptional-alice.png',
    },
    loser: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
  },
  {
    id: 3993,
    dancedAt: '2022-06-12T07:07:59.589Z',
    winner: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
    loser: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
  },
  {
    id: 3992,
    dancedAt: '2022-06-12T07:07:59.247Z',
    winner: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
    loser: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
  },
  {
    id: 3991,
    dancedAt: '2022-06-12T07:07:58.854Z',
    winner: {
      id: 37,
      name: 'Eloquent Teresa',
      powermove: 'Just-in-time Compilation',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/eloquent-teresa.png',
    },
    loser: {
      id: 36,
      name: 'Functional Chris',
      powermove: 'Subscribing Kangaroo',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/functional-chris.png',
    },
  },
  {
    id: 3990,
    dancedAt: '2022-06-12T07:07:58.581Z',
    winner: {
      id: 13,
      name: 'General Garcia',
      powermove: 'Constructor Overloading',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/gerneral-garcia.png',
    },
    loser: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
  },
  {
    id: 3989,
    dancedAt: '2022-06-12T07:04:28.736Z',
    winner: {
      id: 40,
      name: 'Rational Randy',
      powermove: 'Kicking Koala',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/rational-randy.png',
    },
    loser: {
      id: 36,
      name: 'Functional Chris',
      powermove: 'Subscribing Kangaroo',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/functional-chris.png',
    },
  },
  {
    id: 3988,
    dancedAt: '2022-06-12T07:04:28.316Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 11,
      name: 'Dancing Jorge',
      powermove: 'Privilege Escalation',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/dancing-jorge.png',
    },
  },
  {
    id: 3987,
    dancedAt: '2022-06-12T07:04:28.191Z',
    winner: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
    loser: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
  },
  {
    id: 3986,
    dancedAt: '2022-06-12T07:04:27.561Z',
    winner: {
      id: 8,
      name: 'Decisive Sarah',
      powermove: 'Smashing Pineapple',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/decisive-sarah.png',
    },
    loser: {
      id: 13,
      name: 'General Garcia',
      powermove: 'Constructor Overloading',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/gerneral-garcia.png',
    },
  },
  {
    id: 3985,
    dancedAt: '2022-06-12T07:04:06.531Z',
    winner: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
    loser: {
      id: 4,
      name: 'Hilarious Jack',
      powermove: 'Yielding Yak',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/hilarious-jack.png',
    },
  },
  {
    id: 3984,
    dancedAt: '2022-06-12T07:04:05.833Z',
    winner: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
    loser: {
      id: 30,
      name: 'Hipster Kate',
      powermove: 'Dancing Frog',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/hipster-kate.png',
    },
  },
  {
    id: 3983,
    dancedAt: '2022-06-12T07:04:05.398Z',
    winner: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
    loser: {
      id: 22,
      name: 'Rebasing Isabel',
      powermove: 'Path Traversal',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/rebasing-isabel.png',
    },
  },
  {
    id: 3982,
    dancedAt: '2022-06-12T07:04:04.760Z',
    winner: {
      id: 13,
      name: 'General Garcia',
      powermove: 'Constructor Overloading',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/gerneral-garcia.png',
    },
    loser: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
  },
  {
    id: 3981,
    dancedAt: '2022-06-11T11:16:54.208Z',
    winner: {
      id: 30,
      name: 'Hipster Kate',
      powermove: 'Dancing Frog',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/hipster-kate.png',
    },
    loser: {
      id: 22,
      name: 'Rebasing Isabel',
      powermove: 'Path Traversal',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/rebasing-isabel.png',
    },
  },
  {
    id: 3980,
    dancedAt: '2022-06-11T11:16:52.885Z',
    winner: {
      id: 13,
      name: 'General Garcia',
      powermove: 'Constructor Overloading',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/gerneral-garcia.png',
    },
    loser: {
      id: 35,
      name: 'Victor "Void" Smith',
      powermove: 'Swimming Ferret',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/victor-void-smith.png',
    },
  },
  {
    id: 3979,
    dancedAt: '2022-06-11T11:16:52.418Z',
    winner: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
    loser: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
  },
  {
    id: 3978,
    dancedAt: '2022-06-11T11:16:52.270Z',
    winner: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
    loser: {
      id: 8,
      name: 'Decisive Sarah',
      powermove: 'Smashing Pineapple',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/decisive-sarah.png',
    },
  },
  {
    id: 3976,
    dancedAt: '2022-06-11T11:14:05.794Z',
    winner: {
      id: 40,
      name: 'Rational Randy',
      powermove: 'Kicking Koala',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/rational-randy.png',
    },
    loser: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
  },
  {
    id: 3977,
    dancedAt: '2022-06-11T11:14:05.791Z',
    winner: {
      id: 40,
      name: 'Rational Randy',
      powermove: 'Kicking Koala',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/rational-randy.png',
    },
    loser: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
  },
  {
    id: 3975,
    dancedAt: '2022-06-11T11:13:14.938Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
  },
  {
    id: 3974,
    dancedAt: '2022-06-11T11:13:14.932Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
  },
  {
    id: 3973,
    dancedAt: '2022-06-11T11:12:57.257Z',
    winner: {
      id: 24,
      name: 'Merge Mike',
      powermove: 'Protective Otter',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/merge-mike.png',
    },
    loser: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
  },
  {
    id: 3972,
    dancedAt: '2022-06-11T11:12:57.256Z',
    winner: {
      id: 24,
      name: 'Merge Mike',
      powermove: 'Protective Otter',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/merge-mike.png',
    },
    loser: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
  },
  {
    id: 3971,
    dancedAt: '2022-06-11T09:25:21.278Z',
    winner: {
      id: 27,
      name: 'Elastic Eddie',
      powermove: 'Dabbing Penguin',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/elastic-eddie.png',
    },
    loser: {
      id: 9,
      name: 'Efficient Linda',
      powermove: 'Relaxing Sloth',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/erfficient-linda.png',
    },
  },
  {
    id: 3970,
    dancedAt: '2022-06-11T09:25:21.273Z',
    winner: {
      id: 27,
      name: 'Elastic Eddie',
      powermove: 'Dabbing Penguin',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/elastic-eddie.png',
    },
    loser: {
      id: 9,
      name: 'Efficient Linda',
      powermove: 'Relaxing Sloth',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/erfficient-linda.png',
    },
  },
  {
    id: 3969,
    dancedAt: '2022-06-11T09:24:55.278Z',
    winner: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3968,
    dancedAt: '2022-06-11T09:24:55.274Z',
    winner: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3967,
    dancedAt: '2022-06-11T09:12:52.402Z',
    winner: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
    loser: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
  },
  {
    id: 3966,
    dancedAt: '2022-06-11T09:12:52.399Z',
    winner: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
    loser: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
  },
  {
    id: 3965,
    dancedAt: '2022-06-11T09:08:06.297Z',
    winner: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 3964,
    dancedAt: '2022-06-11T09:08:06.290Z',
    winner: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 3963,
    dancedAt: '2022-06-11T08:51:02.798Z',
    winner: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
    loser: {
      id: 11,
      name: 'Dancing Jorge',
      powermove: 'Privilege Escalation',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/dancing-jorge.png',
    },
  },
  {
    id: 3962,
    dancedAt: '2022-06-11T08:51:02.795Z',
    winner: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
    loser: {
      id: 11,
      name: 'Dancing Jorge',
      powermove: 'Privilege Escalation',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/dancing-jorge.png',
    },
  },
  {
    id: 3961,
    dancedAt: '2022-06-11T08:47:02.376Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 3960,
    dancedAt: '2022-06-11T08:47:02.362Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 3959,
    dancedAt: '2022-06-11T08:47:00.861Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 3958,
    dancedAt: '2022-06-11T08:47:00.844Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
  },
  {
    id: 3957,
    dancedAt: '2022-06-11T08:46:16.124Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3956,
    dancedAt: '2022-06-11T08:46:16.122Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3955,
    dancedAt: '2022-06-11T08:45:42.518Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3954,
    dancedAt: '2022-06-11T08:45:42.507Z',
    winner: {
      id: 28,
      name: 'Endearing Fred',
      powermove: 'Lazy Loading',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/endearing-fred.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3953,
    dancedAt: '2022-06-11T07:16:18.284Z',
    winner: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
    loser: {
      id: 18,
      name: 'Exceptional Alice',
      powermove: 'Heap Allocation',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/exceptional-alice.png',
    },
  },
  {
    id: 3952,
    dancedAt: '2022-06-11T07:16:18.277Z',
    winner: {
      id: 6,
      name: 'Flexible Stuart',
      powermove: 'Searching Swan',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/flexible-stuart.png',
    },
    loser: {
      id: 18,
      name: 'Exceptional Alice',
      powermove: 'Heap Allocation',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/exceptional-alice.png',
    },
  },
  {
    id: 3951,
    dancedAt: '2022-06-11T07:08:41.512Z',
    winner: {
      id: 1,
      name: 'Funky Joe',
      powermove: 'Spinning Turtle',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/funky-joe.png',
    },
    loser: {
      id: 2,
      name: 'Ternary Tim',
      powermove: 'Type Coercion',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/ternary-tim.png',
    },
  },
  {
    id: 3950,
    dancedAt: '2022-06-11T01:18:10.808Z',
    winner: {
      id: 1,
      name: 'Funky Joe',
      powermove: 'Spinning Turtle',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/funky-joe.png',
    },
    loser: {
      id: 2,
      name: 'Ternary Tim',
      powermove: 'Type Coercion',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/ternary-tim.png',
    },
  },
  {
    id: 3949,
    dancedAt: '2022-06-09T08:28:39.014Z',
    winner: {
      id: 34,
      name: 'Agile Anna',
      powermove: 'Pretzel Hop',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/agile-anna.png',
    },
    loser: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
  },
  {
    id: 3948,
    dancedAt: '2022-06-09T08:28:39.002Z',
    winner: {
      id: 38,
      name: 'Spinning Christina',
      powermove: 'Optional Chaining',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/spinning-christina.png',
    },
    loser: {
      id: 8,
      name: 'Decisive Sarah',
      powermove: 'Smashing Pineapple',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/decisive-sarah.png',
    },
  },
  {
    id: 3947,
    dancedAt: '2022-06-09T08:28:38.908Z',
    winner: {
      id: 14,
      name: 'Infinity Sam',
      powermove: 'Database Migration',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/infinity-sam.png',
    },
    loser: {
      id: 24,
      name: 'Merge Mike',
      powermove: 'Protective Otter',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/merge-mike.png',
    },
  },
  {
    id: 3946,
    dancedAt: '2022-06-09T08:28:38.809Z',
    winner: {
      id: 40,
      name: 'Rational Randy',
      powermove: 'Kicking Koala',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/rational-randy.png',
    },
    loser: {
      id: 5,
      name: 'Productive Paula',
      powermove: 'Celebrating Lobster',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/productive-paula.png',
    },
  },
  {
    id: 3945,
    dancedAt: '2022-06-09T08:28:38.481Z',
    winner: {
      id: 39,
      name: 'Zero-Downtime Sophie',
      powermove: 'Duck Typing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/zero-downtime-sophie.png',
    },
    loser: {
      id: 1,
      name: 'Funky Joe',
      powermove: 'Spinning Turtle',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/funky-joe.png',
    },
  },
  {
    id: 3944,
    dancedAt: '2022-06-09T08:22:14.600Z',
    winner: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
    loser: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
  },
  {
    id: 3943,
    dancedAt: '2022-06-09T08:22:14.510Z',
    winner: {
      id: 30,
      name: 'Hipster Kate',
      powermove: 'Dancing Frog',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/hipster-kate.png',
    },
    loser: {
      id: 19,
      name: 'Sliding Stephanie',
      powermove: 'Cache Invalidation',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/sliding-stephanie.png',
    },
  },
  {
    id: 3942,
    dancedAt: '2022-06-09T08:22:14.416Z',
    winner: {
      id: 11,
      name: 'Dancing Jorge',
      powermove: 'Privilege Escalation',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/dancing-jorge.png',
    },
    loser: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
  },
  {
    id: 3941,
    dancedAt: '2022-06-09T08:22:14.402Z',
    winner: {
      id: 18,
      name: 'Exceptional Alice',
      powermove: 'Heap Allocation',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/exceptional-alice.png',
    },
    loser: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
  },
  {
    id: 3940,
    dancedAt: '2022-06-09T08:22:13.735Z',
    winner: {
      id: 21,
      name: 'Versatile Hector',
      powermove: 'Exception Handling',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/versatile-hector.png',
    },
    loser: {
      id: 40,
      name: 'Rational Randy',
      powermove: 'Kicking Koala',
      experience: 12,
      outOfOrder: false,
      avatar: 'https://robohash.org/rational-randy.png',
    },
  },
  {
    id: 3939,
    dancedAt: '2022-06-09T07:40:30.403Z',
    winner: {
      id: 29,
      name: 'Positive Anna',
      powermove: 'Tree Shaking',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/positive-anna.png',
    },
    loser: {
      id: 7,
      name: 'Lisa "Root" Allen',
      powermove: 'Fork Join',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/lisa-root-allen.png',
    },
  },
  {
    id: 3938,
    dancedAt: '2022-06-09T07:40:30.304Z',
    winner: {
      id: 4,
      name: 'Hilarious Jack',
      powermove: 'Yielding Yak',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/hilarious-jack.png',
    },
    loser: {
      id: 26,
      name: 'Confident Carol',
      powermove: 'Brute Force Detection',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/confident-carol.png',
    },
  },
  {
    id: 3937,
    dancedAt: '2022-06-09T07:40:30.206Z',
    winner: {
      id: 34,
      name: 'Agile Anna',
      powermove: 'Pretzel Hop',
      experience: 5,
      outOfOrder: false,
      avatar: 'https://robohash.org/agile-anna.png',
    },
    loser: {
      id: 22,
      name: 'Rebasing Isabel',
      powermove: 'Path Traversal',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/rebasing-isabel.png',
    },
  },
  {
    id: 3936,
    dancedAt: '2022-06-09T07:40:30.103Z',
    winner: {
      id: 2,
      name: 'Ternary Tim',
      powermove: 'Type Coercion',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/ternary-tim.png',
    },
    loser: {
      id: 17,
      name: 'Danger Dan',
      powermove: 'Floating Unicorn',
      experience: 15,
      outOfOrder: false,
      avatar: 'https://robohash.org/danger-dan.png',
    },
  },
  {
    id: 3935,
    dancedAt: '2022-06-09T07:40:29.269Z',
    winner: {
      id: 12,
      name: 'Fred "Detail-Oriented" Miller',
      powermove: 'Deep Cloning',
      experience: 9,
      outOfOrder: false,
      avatar: 'https://robohash.org/fred-miller.png',
    },
    loser: {
      id: 24,
      name: 'Merge Mike',
      powermove: 'Protective Otter',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/merge-mike.png',
    },
  },
  {
    id: 3934,
    dancedAt: '2022-06-09T07:31:13.997Z',
    winner: {
      id: 27,
      name: 'Elastic Eddie',
      powermove: 'Dabbing Penguin',
      experience: 11,
      outOfOrder: false,
      avatar: 'https://robohash.org/elastic-eddie.png',
    },
    loser: {
      id: 31,
      name: 'Honest Mark',
      powermove: 'Argument Destructuring',
      experience: 8,
      outOfOrder: false,
      avatar: 'https://robohash.org/honest-mark.png',
    },
  },
  {
    id: 3933,
    dancedAt: '2022-06-09T07:31:13.907Z',
    winner: {
      id: 29,
      name: 'Positive Anna',
      powermove: 'Tree Shaking',
      experience: 10,
      outOfOrder: false,
      avatar: 'https://robohash.org/positive-anna.png',
    },
    loser: {
      id: 25,
      name: 'Charismatic Valeria',
      powermove: 'Secondary Indexing',
      experience: 7,
      outOfOrder: false,
      avatar: 'https://robohash.org/charismatic-valeria.png',
    },
  },
];